### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Api'

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-convergence#2]
while executing api = snappi_convergence.api(location=snappi_api_serv_ip + ':' + str(snappi_api_serv_port),ext='ixnetwork')
getting the error mentioned in the title

**Comment by ANISH-GOTTAPU** [comment]
As discussed, since same name `snappi_convergence` is used for the library and the internal file the import statement is taking the local file and creating the error in Python2.7.

**Comment by alakendu** [comment]
Fix should available in latest snappi_ixnetwork.

pip install snappi_ixnetwork[dev]  to get latest one.

**Comment by selldinesh** [comment]
yes, it works with latest version.Thanks
