### ISSUE TITLE
Unable to get the name of the bgpv4route

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-convergence#3]
Created BGP config with below snippet
            ethernet_stack = config.devices[i-1].ethernet
            ethernet_stack.name = 'Ethernet %d'%i
            ipv4_stack = ethernet_stack.ipv4
            ipv4_stack.name = 'IPv4 %d'%i
            ipv4_stack.address = tgen_ports[i-1]['ip']
            ipv4_stack.gateway = tgen_ports[i-1]['peer_ip']
            ipv4_stack.prefix = tgen_ports[i-1]['prefix']
            bgpv4_stack=ipv4_stack.bgpv4
            bgpv4_stack.name = 'BGP %d'%i
            bgpv4_stack.as_type = BGP_TYPE
            bgpv4_stack.dut_address = tgen_ports[i-1]['peer_ip']
            bgpv4_stack.as_number = TGEN_AS_NUM
            route_range = bgpv4_stack.bgpv4_routes.bgpv4route(name="Network Group %d"%i)[-1]
            route_range.addresses.bgpv4routeaddress(address='200.1.0.1', prefix=32, count=1000, step=1)

After creation, trying to get the name of the Network Group using

config.devices[1].ethernet.ipv4.bgpv4.bgpv4_routes.bgpv4route.name

getting the error AttributeError: 'function' object has no attribute 'name'

**Comment by ashutshkumr** [comment]
Per confirmation from @selldinesh following works:

```python
for d in config.devices:
    if d.name in ['rx_device1', 'rx_device2']:
        for r in d.ethernet.ipv4.bgpv4.bgpv4_routes:
            print(r.name)
            print(r.addresses)
```
