### ISSUE TITLE
convergence value from metrics is different from actual value

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-convergence#4]
Manually calculated the Packet loss duration value using dp_convergence = (tx_frames - rx_frames) * 1000 / tx_frame_rate which gives 3.3 ms ( this is matching the value as seen in traffic item statistics )

based on sample in https://github.com/open-traffic-generator/snappi-tests/pull/19/files , tried the below snippet

            request = cvg_api.convergence_request()
            request.convergence.flow_names = []
            convergence_metrics = cvg_api.get_results(request).flow_convergence
            for metrics in convergence_metrics:
                logger.info(metrics.control_plane_data_plane_convergence_us) -> which gives 15.3 ms ( this is not correct )

**Comment by ashutshkumr** [comment]
@selldinesh what is the data_plane_data_plane_convergence_us value you're seeing ? since CPDP value is different from DPDP.

**Comment by selldinesh** [comment]
@ashutshkumr data_plane_data_plane_convergence_us value was 15377 for link down operation

**Comment by ANISH-GOTTAPU** [comment]
@selldinesh : `Packet Loss Duration` and `CP/DP convergence` are different. The Packet Loss Duration you are seeing is when traffic is still in running state and is momentary

Traffic is in running state
---------------------------
![image](https://user-images.githubusercontent.com/48308607/123212223-239b2680-d4e2-11eb-826f-84a363c0c800.png)

After Traffic is stopped (Tx and Rx sync will be proper and you can see no loss)
-------------------------
![image](https://user-images.githubusercontent.com/48308607/123212363-50e7d480-d4e2-11eb-8012-8864270e2193.png)

**Comment by ANISH-GOTTAPU** [comment]
closing the issue as discussed
