### ISSUE TITLE
int(get_flow_stats(cvg_api)[0].frames_rx_rate is not returning the correct value that is being shown in GUI

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-convergence#5]
As shown in below log

|---- Test_Port_2 Link Flap Iteration : 1 ----|
07:14:32 bgp_convergence_helper.get_avg_dpdp_conv L0277 INFO   | Starting Traffic
07:14:54 connection._info                         L0243 INFO   | [ixn-otg] Devices start 21.051s
07:14:58 connection._info                         L0243 INFO   | [ixn-otg] Flows generate/apply 4.090s
07:15:12 connection._info                         L0243 INFO   | [ixn-otg] Flows clear statistics 13.692s
07:15:12 connection._info                         L0243 INFO   | [ixn-otg] Captures start 0.000s
07:15:15 connection._info                         L0243 INFO   | [ixn-otg] Flows start 2.998s
07:15:15 utilities.wait                           L0043 INFO   | Pause 20 seconds, reason: For Traffic To start
07:15:37 bgp_convergence_helper.get_avg_dpdp_conv L0286 INFO   | Simulating Link Failure on Test_Port_2 link
07:15:37 connection._info                         L0243 INFO   | [ixn-otg] Link State operation 0.082s
07:15:37 utilities.wait                           L0043 INFO   | Pause 20 seconds, reason: For Link to go down
07:15:59 bgp_convergence_helper.get_avg_dpdp_conv L0294 INFO   | Traffic has converged after link flap: TxFrameRate:11973180,**RxFrameRate:11973180**

07:24:13 bgp_convergence_helper.get_avg_dpdp_conv L0275 INFO   | |---- Test_Port_3 Link Flap Iteration : 1 ----|
07:24:13 bgp_convergence_helper.get_avg_dpdp_conv L0277 INFO   | Starting Traffic
07:24:27 connection._info                         L0243 INFO   | [ixn-otg] Devices start 13.525s
07:24:38 connection._info                         L0243 INFO   | [ixn-otg] Flows clear statistics 11.503s
07:24:38 connection._info                         L0243 INFO   | [ixn-otg] Captures start 0.000s
07:24:42 connection._info                         L0243 INFO   | [ixn-otg] Flows start 2.865s
07:24:42 utilities.wait                           L0043 INFO   | Pause 20 seconds, reason: For Traffic To start
07:25:03 bgp_convergence_helper.get_avg_dpdp_conv L0286 INFO   | Simulating Link Failure on Test_Port_3 link
07:25:03 connection._info                         L0243 INFO   | [ixn-otg] Link State operation 0.070s
07:25:03 utilities.wait                           L0043 INFO   | Pause 20 seconds, reason: For Link to go down
07:25:25 bgp_convergence_helper.get_avg_dpdp_conv L0294 INFO   | Traffic has not converged after link flap: TxFrameRate:11973180,**RxFrameRate:0**

In GUI i see tx and rx frame rates are matching with value 11973180, but int(get_flow_stats(cvg_api)[0].frames_rx_rate) returns value 0

In case of RIB-IN convergence , the rx frame rate is some random value

| |---- RIB-IN Convergence test, Iteration : 1 ----|
08:41:06 bgp_convergence_helper.get_RIB_IN_conver L0441 INFO   | Withdraw All Routes before starting traffic
08:41:08 connection._info                         L0243 INFO   | [ixn-otg] Setting route state 1.676s
08:41:08 utilities.wait                           L0043 INFO   | Pause 20 seconds, reason: For Routes to be withdrawn
08:41:28 bgp_convergence_helper.get_RIB_IN_conver L0448 INFO   | Starting Traffic
08:41:46 connection._info                         L0243 INFO   | [ixn-otg] Devices start 18.263s
08:41:51 connection._info                         L0243 INFO   | [ixn-otg] Flows generate/apply 3.991s
08:42:04 connection._info                         L0243 INFO   | [ixn-otg] Flows clear statistics 13.697s
08:42:04 connection._info                         L0243 INFO   | [ixn-otg] Captures start 0.000s
08:42:08 connection._info                         L0243 INFO   | [ixn-otg] Flows start 3.093s
08:42:08 utilities.wait                           L0043 INFO   | Pause 20 seconds, reason: For Traffic To start
08:42:29 bgp_convergence_helper.get_RIB_IN_conver L0460 INFO   | Advertising all Routes from ['Network Group 2', 'Network Group 3']
08:42:31 connection._info                         L0243 INFO   | [ixn-otg] Setting route state 1.882s
08:42:32 utilities.wait                           L0043 INFO   | Pause 20 seconds, reason: For all routes to be ADVERTISED
>           **assert int(flow.frames_tx_rate)==int(flow.frames_rx_rate), "Traffic has not converged after route advertisement: TxFrameRate:{},RxFrameRate:{}".format(int(flow.frames_tx_rate),int(flow.frames_rx_rate))**
E           AssertionError: Traffic has not converged after route advertisement: TxFrameRate:11973180,**RxFrameRate:5986590**

**Comment by ANISH-GOTTAPU** [comment]
@selldinesh : I assume you are taking the stats on which you have triggered the link down

In my scenario, I did withdraw on path1(`port_rx: rx1`) , if we take flow stats of this the rx_frame_rate would be 0. Please pick the other flow where the lindown/withdraw is not done 

- bytes_rx: 30892524544
  bytes_tx: 0
  frames_rx: 30168481
  **frames_rx_rate: 0.0**
  frames_tx: 178940876
  **frames_tx_rate: 5986590.0**
  loss: null
  name: convergence_test
  **port_rx: rx1**
  port_tx: tx
  transmit: started
- bytes_rx: 152342919168
  bytes_tx: 0
  frames_rx: 148772382
  **frames_rx_rate: 5986590.0**
  frames_tx: 178940876
  **frames_tx_rate: 5986590.0**
  loss: null
  name: convergence_test
  **port_rx: rx2**
  port_tx: tx
  transmit: started

**Comment by ANISH-GOTTAPU** [comment]
closing the issue as discussed
